spring.application.name=restaurant-backend
spring.datasource.url=jdbc:mysql://altaria.proxy.rlwy.net:33264/restaurant_db?sslMode=REQUIRED
spring.datasource.username=root
spring.datasource.password=lJKHkpCOCWWopGjVfsnHswOBkUMBqTSF

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
